basePath: /recipes
layout: recipe
toc:
  - items:
      - index
  - title: Customer 360
    items:
      - customer-360/clickstream
  - title: Retail
    items:
      - retail/inventory
  - title: Security
    items:
      - security/ssh-attack
