basePath: /recipes
layout: recipe
toc:
  - items:
      - index
  - title: Customer 360
    items:
      - customer-360/clickstream
  - title: Retail
    items:
      - retail/inventory
      - retail/fleet_management
  - title: Security
    items:
      - security/ssh-attack
  - title: Financial Services
    items:
      - fin-serv/credit-card-activity
      - fin-serv/denormalization
      - fin-server/payment-status-check
  - title: Operations
    items:
      - operations/salesforce
