INSERT INTO message_stream ( send_id, recv_id, message ) VALUES ( 1, 2, 'Hello' );
INSERT INTO message_stream ( send_id, recv_id, message ) VALUES ( 1, 3, 'Hello' );
INSERT INTO message_stream ( send_id, recv_id, message ) VALUES ( 2, 1, 'Hey there' );
INSERT INTO message_stream ( send_id, recv_id, message ) VALUES ( 1, 2, 'What''s going on?' );
INSERT INTO message_stream ( send_id, recv_id, message ) VALUES ( 3, 4, 'Hi' );
INSERT INTO message_stream ( send_id, recv_id, message ) VALUES ( 3, 4, 'Hello' );
INSERT INTO message_stream ( send_id, recv_id, message ) VALUES ( 5, 4, 'Hi' );
INSERT INTO message_stream ( send_id, recv_id, message ) VALUES ( 4, 5, 'Well hi to you too.' );
INSERT INTO message_stream ( send_id, recv_id, message ) VALUES ( 3, 4, 'I''d like to chat.' );
INSERT INTO message_stream ( send_id, recv_id, message ) VALUES ( 5, 4, 'Would you care to discuss the price of fish?' );
