SELECT  CUSTOMER_NAME
      , CUSTOMER_EMAIL
      , CUSTOMER_PHONE
      , FLIGHT_DESTINATION
      , FLIGHT_CODE
      , FLIGHT_SCHEDULED_DEP 
      , FU.UPDATED_DEP AS FLIGHT_UPDATED_DEP
      , FU.REASON      AS FLIGHT_CHANGE_REASON 
  FROM FLIGHT_UPDATES FU
        INNER JOIN CUSTOMER_FLIGHTS_REKEYED CB
        ON FU.FLIGHT_ID = CB.FLIGHT_ID
EMIT CHANGES;
